# Generated by Django 5.2.7 on 2025-11-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='replaces',
            field=models.ForeignKey(
                blank=True,
                help_text='The maintenance event that this event replaces (for rescheduled events)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replaced_by_maintenance',
                to='vendor_notification.maintenance',
                verbose_name='Replaces Maintenance'
            ),
        ),
    ]
