# Generated by Django 5.2.13 on 2026-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0227_alter_interface_speed_bigint"),
        ("notices", "0008_alter_maintenance_end_alter_maintenance_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="locations",
            field=models.ManyToManyField(blank=True, related_name="impacts", to="dcim.location"),
        ),
        migrations.AddField(
            model_name="impact",
            name="sites",
            field=models.ManyToManyField(blank=True, related_name="impacts", to="dcim.site"),
        ),
    ]
