# Generated by Django 6.0.6 on 2026-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0010_backfill_impact_sites_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparednotification',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preparednotification',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
